# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title: 				ACQ
tagline: 			Make Dope Shit
url: 					http://acqtaste.club
paginate:     1  # not sure what this does
baseurl:      ""


# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  # sass_dir:          _sass
  sass_dir:          assets/css
  style:            :compressed

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/poole/poole
